// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CockpitDisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenTow
void ui_ScreenTow_screen_init(void);
lv_obj_t *ui_ScreenTow;
lv_obj_t *ui_arcBatt;
lv_obj_t *ui_lblBatt;
lv_obj_t *ui_arcGforce;
lv_obj_t *ui_lblGforce;
lv_obj_t *ui_PanelState;
lv_obj_t *ui_lblState;
lv_obj_t *ui_lblStufe;
lv_obj_t *ui_PanelMeter;
lv_obj_t *ui_lblMeters;
lv_obj_t *ui_lblLine;
lv_obj_t *ui_PanelFtar;
lv_obj_t *ui_lblFsoll;
lv_obj_t *ui_lblForceSoll;
lv_obj_t *ui_PanelFtar1;
lv_obj_t *ui_lblFist;
lv_obj_t *ui_lblForceIst;
lv_obj_t *ui_ImageWindDir;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_windpfeil_[1] = {&ui_img_windpfeil_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenTow_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenTow);
}
