// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CockpitDisplay

#ifndef _COCKPITDISPLAY_UI_H
#define _COCKPITDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenTow
void ui_ScreenTow_screen_init(void);
extern lv_obj_t *ui_ScreenTow;
extern lv_obj_t *ui_arcBatt;
extern lv_obj_t *ui_lblBatt;
extern lv_obj_t *ui_arcGforce;
extern lv_obj_t *ui_lblGforce;
extern lv_obj_t *ui_PanelState;
extern lv_obj_t *ui_lblState;
extern lv_obj_t *ui_lblStufe;
extern lv_obj_t *ui_PanelMeter;
extern lv_obj_t *ui_lblMeters;
extern lv_obj_t *ui_lblLine;
extern lv_obj_t *ui_PanelFtar;
extern lv_obj_t *ui_lblFsoll;
extern lv_obj_t *ui_lblForceSoll;
extern lv_obj_t *ui_PanelFtar1;
extern lv_obj_t *ui_lblFist;
extern lv_obj_t *ui_lblForceIst;
extern lv_obj_t *ui_ImageWindDir;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_windpfeil_2_png);   // assets/WindPfeil_2.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
