// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CockpitDisplay

#include "../ui.h"

void ui_ScreenTow_screen_init(void)
{
ui_ScreenTow = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenTow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
//lv_obj_set_style_bg_img_src( ui_ScreenTow, &TemporaryImage, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_arcBatt = lv_arc_create(ui_ScreenTow);
lv_obj_set_width( ui_arcBatt, 240);
lv_obj_set_height( ui_arcBatt, 240);
lv_obj_set_align( ui_arcBatt, LV_ALIGN_CENTER );
lv_arc_set_value(ui_arcBatt, 5);
lv_arc_set_bg_angles(ui_arcBatt,130,230);
lv_obj_set_style_bg_color(ui_arcBatt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arcBatt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_arcBatt, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arcBatt, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_arcBatt, lv_color_hex(0x1AFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arcBatt, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_arcBatt, lv_color_hex(0xD50000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arcBatt, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lblBatt = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblBatt, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_lblBatt, LV_SIZE_CONTENT);   /// 5
lv_obj_set_x( ui_lblBatt, -55 );
lv_obj_set_y( ui_lblBatt, -94 );
lv_obj_set_align( ui_lblBatt, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblBatt,"BAT");
lv_obj_set_style_text_color(ui_lblBatt, lv_color_hex(0xDAC207), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblBatt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblBatt, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblBatt, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arcGforce = lv_arc_create(ui_ScreenTow);
lv_obj_set_width( ui_arcGforce, 240);
lv_obj_set_height( ui_arcGforce, 240);
lv_obj_set_align( ui_arcGforce, LV_ALIGN_CENTER );
lv_arc_set_range(ui_arcGforce, 0,10);
lv_arc_set_bg_angles(ui_arcGforce,-70,50);
lv_arc_set_mode(ui_arcGforce, LV_ARC_MODE_REVERSE);
lv_obj_set_style_arc_color(ui_arcGforce, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arcGforce, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_arcGforce, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arcGforce, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_arcGforce, lv_color_hex(0xD50000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arcGforce, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lblGforce = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblGforce, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_lblGforce, LV_SIZE_CONTENT);   /// 5
lv_obj_set_x( ui_lblGforce, 53 );
lv_obj_set_y( ui_lblGforce, -98 );
lv_obj_set_align( ui_lblGforce, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblGforce,"g");
lv_obj_set_style_text_color(ui_lblGforce, lv_color_hex(0xDAC207), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblGforce, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblGforce, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblGforce, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelState = lv_obj_create(ui_ScreenTow);
lv_obj_set_width( ui_PanelState, 70);
lv_obj_set_height( ui_PanelState, 60);
lv_obj_set_x( ui_PanelState, 0 );
lv_obj_set_y( ui_PanelState, 15 );
lv_obj_set_align( ui_PanelState, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_PanelState, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelState, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelState, lv_color_hex(0x9B9B9B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelState, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblState = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblState, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_lblState, LV_SIZE_CONTENT);   /// 5
lv_obj_set_x( ui_lblState, 0 );
lv_obj_set_y( ui_lblState, 16 );
lv_obj_set_align( ui_lblState, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblState,"State");
lv_obj_set_style_text_color(ui_lblState, lv_color_hex(0xDAC207), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblState, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblState, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblState, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblStufe = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblStufe, 60);
lv_obj_set_height( ui_lblStufe, 50);
lv_obj_set_x( ui_lblStufe, 0 );
lv_obj_set_y( ui_lblStufe, 26 );
lv_obj_set_align( ui_lblStufe, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblStufe,"0");
lv_obj_set_style_text_color(ui_lblStufe, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblStufe, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblStufe, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblStufe, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblStufe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblStufe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMeter = lv_obj_create(ui_ScreenTow);
lv_obj_set_width( ui_PanelMeter, 125);
lv_obj_set_height( ui_PanelMeter, 60);
lv_obj_set_x( ui_PanelMeter, 0 );
lv_obj_set_y( ui_PanelMeter, 160 );
lv_obj_set_align( ui_PanelMeter, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_PanelMeter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelMeter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMeter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMeter, lv_color_hex(0x9B9B9B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMeter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblMeters = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblMeters, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_lblMeters, LV_SIZE_CONTENT);   /// 5
lv_obj_set_x( ui_lblMeters, 0 );
lv_obj_set_y( ui_lblMeters, 161 );
lv_obj_set_align( ui_lblMeters, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblMeters,"meters out");
lv_obj_set_style_text_color(ui_lblMeters, lv_color_hex(0xDAC207), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblMeters, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblMeters, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblMeters, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblLine = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblLine, 120);
lv_obj_set_height( ui_lblLine, 50);
lv_obj_set_x( ui_lblLine, 0 );
lv_obj_set_y( ui_lblLine, 171 );
lv_obj_set_align( ui_lblLine, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblLine,"0");
lv_obj_set_style_text_color(ui_lblLine, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblLine, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblLine, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblLine, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblLine, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblLine, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFtar = lv_obj_create(ui_ScreenTow);
lv_obj_set_width( ui_PanelFtar, 95);
lv_obj_set_height( ui_PanelFtar, 60);
lv_obj_set_x( ui_PanelFtar, -50 );
lv_obj_set_y( ui_PanelFtar, 88 );
lv_obj_set_align( ui_PanelFtar, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_PanelFtar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelFtar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelFtar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelFtar, lv_color_hex(0x9B9B9B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelFtar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblFsoll = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblFsoll, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_lblFsoll, LV_SIZE_CONTENT);   /// 5
lv_obj_set_x( ui_lblFsoll, -50 );
lv_obj_set_y( ui_lblFsoll, 89 );
lv_obj_set_align( ui_lblFsoll, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblFsoll,"F target");
lv_obj_set_style_text_color(ui_lblFsoll, lv_color_hex(0xDAC207), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblFsoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblFsoll, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblFsoll, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForceSoll = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblForceSoll, 90);
lv_obj_set_height( ui_lblForceSoll, 50);
lv_obj_set_x( ui_lblForceSoll, -50 );
lv_obj_set_y( ui_lblForceSoll, 99 );
lv_obj_set_align( ui_lblForceSoll, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblForceSoll,"0");
lv_obj_set_style_text_color(ui_lblForceSoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblForceSoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblForceSoll, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblForceSoll, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblForceSoll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblForceSoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFtar1 = lv_obj_create(ui_ScreenTow);
lv_obj_set_width( ui_PanelFtar1, 95);
lv_obj_set_height( ui_PanelFtar1, 60);
lv_obj_set_x( ui_PanelFtar1, 50 );
lv_obj_set_y( ui_PanelFtar1, 88 );
lv_obj_set_align( ui_PanelFtar1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_PanelFtar1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelFtar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelFtar1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelFtar1, lv_color_hex(0x9B9B9B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelFtar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblFist = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblFist, LV_SIZE_CONTENT);  /// 30
lv_obj_set_height( ui_lblFist, LV_SIZE_CONTENT);   /// 5
lv_obj_set_x( ui_lblFist, 50 );
lv_obj_set_y( ui_lblFist, 89 );
lv_obj_set_align( ui_lblFist, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblFist,"F actual");
lv_obj_set_style_text_color(ui_lblFist, lv_color_hex(0xDAC207), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblFist, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblFist, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblFist, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForceIst = lv_label_create(ui_ScreenTow);
lv_obj_set_width( ui_lblForceIst, 90);
lv_obj_set_height( ui_lblForceIst, 50);
lv_obj_set_x( ui_lblForceIst, 50 );
lv_obj_set_y( ui_lblForceIst, 99 );
lv_obj_set_align( ui_lblForceIst, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblForceIst,"0");
lv_obj_set_style_text_color(ui_lblForceIst, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblForceIst, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblForceIst, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblForceIst, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblForceIst, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblForceIst, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWindDir = lv_img_create(ui_ScreenTow);
lv_img_set_src(ui_ImageWindDir, &ui_img_windpfeil_2_png);
lv_obj_set_width( ui_ImageWindDir, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageWindDir, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageWindDir, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWindDir, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWindDir, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_ImageWindDir,1800);

}
