// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: RoundDisplayTest

#include "../ui.h"

void ui_ScreenTow1_screen_init(void)
{
ui_ScreenTow1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenTow1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_ScreenTow1, &TemporaryImage, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_bg_img_src( ui_ScreenTow1, &TemporaryImage, LV_PART_SCROLLBAR | LV_STATE_DEFAULT );

ui_lblStufe1 = lv_label_create(ui_ScreenTow1);
lv_obj_set_width( ui_lblStufe1, 60);
lv_obj_set_height( ui_lblStufe1, 50);
lv_obj_set_x( ui_lblStufe1, 0 );
lv_obj_set_y( ui_lblStufe1, 10 );
lv_obj_set_align( ui_lblStufe1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_lblStufe1,"0");
lv_obj_set_style_text_color(ui_lblStufe1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblStufe1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblStufe1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblStufe1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblStufe1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblStufe1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForceSoll1 = lv_label_create(ui_ScreenTow1);
lv_obj_set_width( ui_lblForceSoll1, 90);
lv_obj_set_height( ui_lblForceSoll1, 50);
lv_obj_set_x( ui_lblForceSoll1, -50 );
lv_obj_set_y( ui_lblForceSoll1, 0 );
lv_obj_set_align( ui_lblForceSoll1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForceSoll1,"0");
lv_obj_set_style_text_color(ui_lblForceSoll1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblForceSoll1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblForceSoll1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblForceSoll1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblForceSoll1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblForceSoll1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblForceIst1 = lv_label_create(ui_ScreenTow1);
lv_obj_set_width( ui_lblForceIst1, 90);
lv_obj_set_height( ui_lblForceIst1, 50);
lv_obj_set_x( ui_lblForceIst1, 50 );
lv_obj_set_y( ui_lblForceIst1, 0 );
lv_obj_set_align( ui_lblForceIst1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblForceIst1,"0");
lv_obj_set_style_text_color(ui_lblForceIst1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblForceIst1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblForceIst1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblForceIst1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblForceIst1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblForceIst1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblLine1 = lv_label_create(ui_ScreenTow1);
lv_obj_set_width( ui_lblLine1, 120);
lv_obj_set_height( ui_lblLine1, 50);
lv_obj_set_x( ui_lblLine1, 0 );
lv_obj_set_y( ui_lblLine1, -20 );
lv_obj_set_align( ui_lblLine1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_lblLine1,"0");
lv_obj_set_style_text_color(ui_lblLine1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblLine1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblLine1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblLine1, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblLine1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblLine1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arcBatt1 = lv_arc_create(ui_ScreenTow1);
lv_obj_set_width( ui_arcBatt1, 240);
lv_obj_set_height( ui_arcBatt1, 240);
lv_obj_set_align( ui_arcBatt1, LV_ALIGN_CENTER );
lv_arc_set_value(ui_arcBatt1, 5);
lv_arc_set_bg_angles(ui_arcBatt1,130,230);

lv_obj_set_style_arc_color(ui_arcBatt1, lv_color_hex(0x1AFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arcBatt1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_arcBatt1, lv_color_hex(0xD50000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arcBatt1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

}
